# discovery-service/src/main/resources/application.yml
server:
  port: 8761

spring:
  application:
    name: discovery-service
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false

management:
  endpoints:
    web:
      exposure:
        include: health,info