# complaint-service/src/main/resources/application-docker.yml
spring:
  config:
    import: optional:configserver:http://config-service:8888
  datasource:
    url: jdbc:postgresql://postgres:5432/complaint_service