server:
  port: 8082

spring:
  application:
    name: complaint-service
  datasource:
    url: jdbc:postgresql://postgres:5432/complaint_service
    username: postgres
    password: postgres
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
