server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: complaint-service
          uri: lb://complaint-service
          predicates:
            - Path=/api/complaints/**
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/api/departments/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
        - id: feedback-service
          uri: lb://feedback-service
          predicates:
            - Path=/api/feedback/**
